services:
  api:
    build: .
    container_name: pki-2fa-microservice
    ports:
      - "8080:8080"
    environment:
      - TZ=UTC
    volumes:
      - seed-data:/data
      - cron-output:/cron
      - ./keys:/app/keys:ro
    restart: unless-stopped

volumes:
  seed-data:
  cron-output:
